// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binarization algorithm for converting grayscale to black-and-white.
 */
export type BinarizationMode = "otsu" | "bradley-roth" | "fixed";
