// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compression codec for bi-level (bitonal) page images.
 */
export type CompressionMode = "ccitt" | "flate";
