// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OcrOptions } from "./OcrOptions";
import type { ProcessingConfigInput } from "./ProcessingConfigInput";

export type EnqueuePayload = { files: Array<string>, outputDir: string, options: OcrOptions, processing: ProcessingConfigInput | null, };
