// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strategy for handling PDF pages that already contain text.
 */
export type ExistingTextMode = "skip" | "rasterize";
