// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { OcrOptions } from "./OcrOptions";

export type HistoryEntry = { id: string, inputPath: string, outputPath: string, status: JobStatus, startedAt: number, finishedAt: number, durationMs: number, options: OcrOptions, };
