// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { OcrOptions } from "./OcrOptions";
import type { ProcessingConfigInput } from "./ProcessingConfigInput";

export type Job = { id: string, inputPath: string, outputPath: string, status: JobStatus, percent: number, startedAt: number | null, finishedAt: number | null, options: OcrOptions, processing: ProcessingConfigInput | null, errorMessage: string | null, };
