// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinarizationMode } from "./BinarizationMode";
import type { CompressionMode } from "./CompressionMode";
import type { DeskewMode } from "./DeskewMode";
import type { ExistingTextMode } from "./ExistingTextMode";
import type { OutputType } from "./OutputType";
import type { PageSegMode } from "./PageSegMode";

export type OcrOptions = { outputType: OutputType, safeMode: boolean, maxConcurrency: number | null, binarization: BinarizationMode, fixedThreshold: number, deskewMode: DeskewMode, denoiseLevel: number, existingText: ExistingTextMode, psm: PageSegMode, compression: CompressionMode, resolutionDpi: number, archiveEnforcement: boolean, languages: string | null, memoryPages: number | null, continueOnError: boolean, password: string | null, };
