// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tesseract page segmentation mode.
 */
export type PageSegMode = "auto" | "block" | "column" | "sparse";
