// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineStatus } from "./PipelineStatus";

/**
 * Per-job progress event sent to the frontend via `pipeline-progress`.
 */
export type PipelineProgress = { 
/**
 * The job this progress event belongs to.
 */
jobId: string, 
/**
 * Current pipeline stage.
 */
status: PipelineStatus, 
/**
 * Current page being processed (1-indexed).
 */
currentPage: number, 
/**
 * Total pages in the current file.
 */
totalPages: number, 
/**
 * Files fully processed so far across the entire queue.
 */
totalFilesProcessed: number, 
/**
 * Total files in the queue when processing began.
 */
totalFilesInQueue: number, 
/**
 * Rolling average milliseconds per page.
 */
averageMsPerPage: number, 
/**
 * Error message if status is Failed.
 */
errorMessage: string | null, };
