// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage of the OCR pipeline for progress reporting.
 */
export type PipelineStatus = "processing" | "ocr" | "completed" | "failed";
