// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input from the frontend for engine-level configuration overrides.
 */
export type ProcessingConfigInput = { 
/**
 * Max number of files to process concurrently (semaphore permits).
 * This is NOT a memory cap — it only gates file concurrency.
 * Actual page memory is bounded by processing pages one at a time
 * via `for_each_page_image` (streaming iterator).
 */
maxConcurrentFiles: number | null, 
/**
 * Path to the tessdata directory (auto-resolved if None).
 */
tessdataPath: string | null, 
/**
 * Tesseract language string (e.g. "eng+spa").
 */
languages: string | null, 
/**
 * Size of the Rayon thread pool for CPU-bound work.
 */
threadPoolSize: number | null, };
